// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VnfUIClient is the client API for VnfUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VnfUIClient interface {
	// ListFunctionSpecs returns a list of Service Function(s) that can be started through the UI.
	ListFunctionSpecs(ctx context.Context, in *ListFunctionSpecsRequest, opts ...grpc.CallOption) (VnfUI_ListFunctionSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type vnfUIClient struct {
	cc grpc.ClientConnInterface
}

func NewVnfUIClient(cc grpc.ClientConnInterface) VnfUIClient {
	return &vnfUIClient{cc}
}

func (c *vnfUIClient) ListFunctionSpecs(ctx context.Context, in *ListFunctionSpecsRequest, opts ...grpc.CallOption) (VnfUI_ListFunctionSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &VnfUI_ServiceDesc.Streams[0], "/v1.VnfUI/ListFunctionSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &vnfUIListFunctionSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VnfUI_ListFunctionSpecsClient interface {
	Recv() (*ListFunctionSpecsResponse, error)
	grpc.ClientStream
}

type vnfUIListFunctionSpecsClient struct {
	grpc.ClientStream
}

func (x *vnfUIListFunctionSpecsClient) Recv() (*ListFunctionSpecsResponse, error) {
	m := new(ListFunctionSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vnfUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.VnfUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VnfUIServer is the server API for VnfUI service.
// All implementations must embed UnimplementedVnfUIServer
// for forward compatibility
type VnfUIServer interface {
	// ListFunctionSpecs returns a list of Service Function(s) that can be started through the UI.
	ListFunctionSpecs(*ListFunctionSpecsRequest, VnfUI_ListFunctionSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedVnfUIServer()
}

// UnimplementedVnfUIServer must be embedded to have forward compatible implementations.
type UnimplementedVnfUIServer struct {
}

func (UnimplementedVnfUIServer) ListFunctionSpecs(*ListFunctionSpecsRequest, VnfUI_ListFunctionSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListFunctionSpecs not implemented")
}
func (UnimplementedVnfUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedVnfUIServer) mustEmbedUnimplementedVnfUIServer() {}

// UnsafeVnfUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VnfUIServer will
// result in compilation errors.
type UnsafeVnfUIServer interface {
	mustEmbedUnimplementedVnfUIServer()
}

func RegisterVnfUIServer(s grpc.ServiceRegistrar, srv VnfUIServer) {
	s.RegisterService(&VnfUI_ServiceDesc, srv)
}

func _VnfUI_ListFunctionSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListFunctionSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VnfUIServer).ListFunctionSpecs(m, &vnfUIListFunctionSpecsServer{stream})
}

type VnfUI_ListFunctionSpecsServer interface {
	Send(*ListFunctionSpecsResponse) error
	grpc.ServerStream
}

type vnfUIListFunctionSpecsServer struct {
	grpc.ServerStream
}

func (x *vnfUIListFunctionSpecsServer) Send(m *ListFunctionSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _VnfUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VnfUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.VnfUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VnfUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VnfUI_ServiceDesc is the grpc.ServiceDesc for VnfUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VnfUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.VnfUI",
	HandlerType: (*VnfUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _VnfUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListFunctionSpecs",
			Handler:       _VnfUI_ListFunctionSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vnf-ui.proto",
}
